/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as PageSectionIndexRouteImport } from './routes/page-section/index'
import { Route as GradientIndexRouteImport } from './routes/gradient/index'
import { Route as FormIndexRouteImport } from './routes/form/index'
import { Route as EasingsIndexRouteImport } from './routes/easings/index'
import { Route as AppShellIndexRouteImport } from './routes/app-shell/index'
import { Route as ThemePageRouteImport } from './routes/theme/page'
import { Route as ErrNotFoundRouteImport } from './routes/err/not-found'
import { Route as BackgroundImagePageRouteImport } from './routes/background-image/page'
import { Route as CategoryPageRouteImport } from './routes/$category/page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSectionIndexRoute = PageSectionIndexRouteImport.update({
  id: '/page-section/',
  path: '/page-section/',
  getParentRoute: () => rootRouteImport,
} as any)
const GradientIndexRoute = GradientIndexRouteImport.update({
  id: '/gradient/',
  path: '/gradient/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormIndexRoute = FormIndexRouteImport.update({
  id: '/form/',
  path: '/form/',
  getParentRoute: () => rootRouteImport,
} as any)
const EasingsIndexRoute = EasingsIndexRouteImport.update({
  id: '/easings/',
  path: '/easings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellIndexRoute = AppShellIndexRouteImport.update({
  id: '/app-shell/',
  path: '/app-shell/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemePageRoute = ThemePageRouteImport.update({
  id: '/theme/page',
  path: '/theme/page',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrNotFoundRoute = ErrNotFoundRouteImport.update({
  id: '/err/not-found',
  path: '/err/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundImagePageRoute = BackgroundImagePageRouteImport.update({
  id: '/background-image/page',
  path: '/background-image/page',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryPageRoute = CategoryPageRouteImport.update({
  id: '/$category/page',
  path: '/$category/page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$category/page': typeof CategoryPageRoute
  '/background-image/page': typeof BackgroundImagePageRoute
  '/err/not-found': typeof ErrNotFoundRoute
  '/theme/page': typeof ThemePageRoute
  '/app-shell/': typeof AppShellIndexRoute
  '/easings/': typeof EasingsIndexRoute
  '/form/': typeof FormIndexRoute
  '/gradient/': typeof GradientIndexRoute
  '/page-section/': typeof PageSectionIndexRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$category/page': typeof CategoryPageRoute
  '/background-image/page': typeof BackgroundImagePageRoute
  '/err/not-found': typeof ErrNotFoundRoute
  '/theme/page': typeof ThemePageRoute
  '/app-shell': typeof AppShellIndexRoute
  '/easings': typeof EasingsIndexRoute
  '/form': typeof FormIndexRoute
  '/gradient': typeof GradientIndexRoute
  '/page-section': typeof PageSectionIndexRoute
  '/search': typeof SearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$category/page': typeof CategoryPageRoute
  '/background-image/page': typeof BackgroundImagePageRoute
  '/err/not-found': typeof ErrNotFoundRoute
  '/theme/page': typeof ThemePageRoute
  '/app-shell/': typeof AppShellIndexRoute
  '/easings/': typeof EasingsIndexRoute
  '/form/': typeof FormIndexRoute
  '/gradient/': typeof GradientIndexRoute
  '/page-section/': typeof PageSectionIndexRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$category/page'
    | '/background-image/page'
    | '/err/not-found'
    | '/theme/page'
    | '/app-shell/'
    | '/easings/'
    | '/form/'
    | '/gradient/'
    | '/page-section/'
    | '/search/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$category/page'
    | '/background-image/page'
    | '/err/not-found'
    | '/theme/page'
    | '/app-shell'
    | '/easings'
    | '/form'
    | '/gradient'
    | '/page-section'
    | '/search'
  id:
    | '__root__'
    | '/'
    | '/$category/page'
    | '/background-image/page'
    | '/err/not-found'
    | '/theme/page'
    | '/app-shell/'
    | '/easings/'
    | '/form/'
    | '/gradient/'
    | '/page-section/'
    | '/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryPageRoute: typeof CategoryPageRoute
  BackgroundImagePageRoute: typeof BackgroundImagePageRoute
  ErrNotFoundRoute: typeof ErrNotFoundRoute
  ThemePageRoute: typeof ThemePageRoute
  AppShellIndexRoute: typeof AppShellIndexRoute
  EasingsIndexRoute: typeof EasingsIndexRoute
  FormIndexRoute: typeof FormIndexRoute
  GradientIndexRoute: typeof GradientIndexRoute
  PageSectionIndexRoute: typeof PageSectionIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-section/': {
      id: '/page-section/'
      path: '/page-section'
      fullPath: '/page-section/'
      preLoaderRoute: typeof PageSectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradient/': {
      id: '/gradient/'
      path: '/gradient'
      fullPath: '/gradient/'
      preLoaderRoute: typeof GradientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/': {
      id: '/form/'
      path: '/form'
      fullPath: '/form/'
      preLoaderRoute: typeof FormIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/easings/': {
      id: '/easings/'
      path: '/easings'
      fullPath: '/easings/'
      preLoaderRoute: typeof EasingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-shell/': {
      id: '/app-shell/'
      path: '/app-shell'
      fullPath: '/app-shell/'
      preLoaderRoute: typeof AppShellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme/page': {
      id: '/theme/page'
      path: '/theme/page'
      fullPath: '/theme/page'
      preLoaderRoute: typeof ThemePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/err/not-found': {
      id: '/err/not-found'
      path: '/err/not-found'
      fullPath: '/err/not-found'
      preLoaderRoute: typeof ErrNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-image/page': {
      id: '/background-image/page'
      path: '/background-image/page'
      fullPath: '/background-image/page'
      preLoaderRoute: typeof BackgroundImagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/page': {
      id: '/$category/page'
      path: '/$category/page'
      fullPath: '/$category/page'
      preLoaderRoute: typeof CategoryPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryPageRoute: CategoryPageRoute,
  BackgroundImagePageRoute: BackgroundImagePageRoute,
  ErrNotFoundRoute: ErrNotFoundRoute,
  ThemePageRoute: ThemePageRoute,
  AppShellIndexRoute: AppShellIndexRoute,
  EasingsIndexRoute: EasingsIndexRoute,
  FormIndexRoute: FormIndexRoute,
  GradientIndexRoute: GradientIndexRoute,
  PageSectionIndexRoute: PageSectionIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
